### ISSUE TITLE
(1.5.X) Linux binaries depend on libmpv.so.1, which is no longer shipped with Debian Stable/Testing

### ISSUE THREAD

**Issue by Soblow** [resucutie/localbooru#34] opened 2024-10-26 21:34 UTC
**Describe the bug**

The Linux binaries & `.deb` package binaries depend on `libmpv.so.1`, which is no longer shipped in Debian Stable/Testing

**To Reproduce**
Steps to reproduce the behaviour:
1. Download v1.5.2 release and install it
2. Try to launch the binary
3. You'll get the following message:
```plaintext
localbooru: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

**Expected behaviour**
The binary should depend on `libmpv.so.2`, and actually start

**Screenshots**
n.a.

**System informations:**
 - OS: Debian Trixie/sid testing (up-to-date as-of 2024-10-26)
 - Package: Raw binaries, or Debian package
 - Version: v1.5.2

**Additional context**
You may use `ldd` to check to what the binary is linked:
```plaintext
$ ldd localbooru
[snip]
	libmpv.so.1 => not found
[snip]
```

Looking on [debian package repository](https://packages.debian.org/search?suite=all&searchon=names&keywords=libmpv) will show that [libmpv1](https://packages.debian.org/bullseye/libmpv1) is only available in Buster (oldoldstable) and Bullseye (oldstable), and that [libmpv2](https://packages.debian.org/trixie/libmpv2) is available in Bookworm (stable) & Trixie/sid (testing).

Some possible workarounds:
- Rebuild the binary to link to the newer library version (not tested)
- Make a link from `libmpv.so.2` to `libmpv.so.1`:
  - Tested, and it allows the program to start
  - This is the easiest workaround but not stable, and definitely **not recommended**
  - If a major version number bump occurred, we can assume that it isn't ABI compatible, and will break in later versions
- Install the `libmpv1` deb package on stable/testing
  - Tested on Trixie, this doesn't work as the package requires other libraries at earlier versions, which would create a FrankenDebian :(
- Extract the library from the `libmpv1` deb package and put it in relevant directory
  - Not tested, but given the above point, I'm pretty sure it won't work as expected

**Comment by resucutie** [comment] 2024-11-02 14:05
Hello. May you test with 1.6.0-prerelease3? I've changed from media-kit to fvp

**Comment by Soblow** [comment] 2024-11-05 23:03
Pre-release 2 & 3 don't have the issue.

**Comment by resucutie** [comment] 2024-11-08 12:46
Closing the issue, as the issue is already fixed

**Closed by resucutie** 2024-11-08 12:46 UTC
